basePath: /
consumes:
- application/json
host: localhost:8080
info:
  description: API to request weather reports
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  title: Weather API.
  version: 1.0.0
paths:
  /scheduler/weather:
    put:
      description: Schedules a job to be performed every 1 hour
      operationId: scheduleJob
      parameters:
      - description: City name
        example: Bogotá
        in: body
        name: city
        required: true
        schema:
          type: string
        x-go-name: City
      - description: |-
          Country name
          Two letter country code
        example: CO
        in: body
        name: country
        required: true
        schema:
          type: string
        x-go-name: Country
      responses:
        "202":
          $ref: '#/responses/jobScheduledResponse'
        "401":
          $ref: '#/responses/badRequestError'
      tags:
      - job
  /weather:
    get:
      description: Returns a weather report given a city and a country
      operationId: getWeather
      parameters:
      - description: City name
        example: Bogotá
        in: path
        name: city
        required: true
        type: string
        x-go-name: City
      - description: Two letter country code
        example: CO
        in: path
        name: country
        required: true
        type: string
        x-go-name: Country
      responses:
        "200":
          $ref: '#/responses/weather'
        "401":
          $ref: '#/responses/badRequestError'
        "404":
          $ref: '#/responses/notFoundError'
      tags:
      - weather
produces:
- application/json
responses:
  badRequestError:
    description: badRequestError
    headers:
      message:
        description: A list of missing fields
        type: string
      status_code:
        description: "400"
        format: int64
        type: integer
  jobScheduledResponse:
    description: jobScheduledResponse
    headers:
      message:
        description: '"Job scheduled"'
        type: string
      status_code:
        description: "202"
        format: int64
        type: integer
  notFoundError:
    description: notFoundError
    headers:
      message:
        description: City not found
        type: string
      status_code:
        description: "404"
        format: int64
        type: integer
  weather:
    description: Weather is the response for GET /weather
    headers:
      cloudiness:
        type: string
      geo_coordinates:
        items:
          format: float
          type: number
        type: array
      humidity:
        type: string
      location_name:
        type: string
      pressure:
        type: string
      requested_time:
        type: string
      sunrise:
        type: string
      sunset:
        type: string
      temperature:
        type: string
      wind:
        type: string
schemes:
- http
swagger: "2.0"
