version: '3.3'
services:
  api:
    container_name: 'api-version-4'
    build: '.'
    ports:
      - '8080:8080'
    depends_on:
      - 'mongo'
    links:
      - mongo
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo-version-4'
    ports:
      - '27100:27017'
